experiment_name: 'On Rent Time Series'
run_tag: 'lgbm training with params'
lgbm_model:
  data:
    train: "../data/train.csv"
    test: "../data/train.csv"
    predict: "../data/predict.csv"
  model_param:
      objective: "regression"
      metric: "mse"
      verbosity: -1
      boosting_type: "gbdt"
      seed: 42
      linear_tree: True
      learning_rate: .2
      min_child_samples: 5
      num_leaves: 31
      num_iterations: 50
  division_split: False
  region_split: False
  feature: [
        'IHSRentalMarket',
        'AvgTemp',
        'AvgPrcp',
        'OnRent_lag_91',
        'OnRent_lag_98',
        'OnRent_lag_105',
        'OnRent_lag_112',
        'OnRent_lag_119',
        'OnRent_lag_126',
        'OnRent_lag_182',
        'OnRent_lag_364',
        'sales_ewm_alpha_095_lag_91',
        'sales_ewm_alpha_095_lag_98',
        'sales_ewm_alpha_095_lag_105',
        'sales_ewm_alpha_095_lag_112',
        'sales_ewm_alpha_095_lag_180',
        'sales_ewm_alpha_095_lag_270',
        'sales_ewm_alpha_095_lag_365',
        'sales_ewm_alpha_09_lag_91',
        'sales_ewm_alpha_09_lag_98',
        'sales_ewm_alpha_09_lag_105',
        'sales_ewm_alpha_09_lag_112',
        'sales_ewm_alpha_09_lag_180',
        'sales_ewm_alpha_09_lag_270',
        'sales_ewm_alpha_09_lag_365',
        'sales_ewm_alpha_08_lag_91',
        'sales_ewm_alpha_08_lag_98',
        'sales_ewm_alpha_08_lag_105',
        'sales_ewm_alpha_08_lag_112',
        'sales_ewm_alpha_08_lag_180',
        'sales_ewm_alpha_08_lag_270',
        'sales_ewm_alpha_08_lag_365',
        'sales_ewm_alpha_07_lag_91',
        'sales_ewm_alpha_07_lag_98',
        'sales_ewm_alpha_07_lag_105',
        'sales_ewm_alpha_07_lag_112',
        'sales_ewm_alpha_07_lag_180',
        'sales_ewm_alpha_07_lag_270',
        'sales_ewm_alpha_07_lag_365',
        'sales_ewm_alpha_05_lag_91',
        'sales_ewm_alpha_05_lag_98',
        'sales_ewm_alpha_05_lag_105',
        'sales_ewm_alpha_05_lag_112',
        'sales_ewm_alpha_05_lag_180',
        'sales_ewm_alpha_05_lag_270',
        'sales_ewm_alpha_05_lag_365',
        'hour',
        'dayofweek',
        'quarter',
        'month',
        'year',
        'dayofyear',
        'sin_day',
        'cos_day',
        'dayofmonth',
        'weekofyear',
        'eq_nm_1030_POWERTROWELS',
        'eq_nm_1045_AIR-POWEREDSCABBLERS',
        'eq_nm_1060_CONCRETEFLOORGRINDERS',
        'eq_nm_1075_CONCRETEPLANERS',
        'eq_nm_1090_DUSTCOLLECTOR&VACUUMS',
        'eq_nm_1150_PORTABLESHOTBLASTERS',
        'eq_nm_115_PORTABLEABRASIVEBLASTERS',
        'eq_nm_1180_CONCRETE&ASPHALTFLOORSAWS-PUSHTYPE',
        'eq_nm_1195_CONCRETEANDMASONRYBLADES',
        'eq_nm_1210_CONCRETEDOWELDRILLS',
        'eq_nm_1225_COREDRILLBITS',
        'eq_nm_1255_CUTOFFSAWSHANDHELD/GAS/AIR/ELECTRIC/HYDRAULIC',
        'eq_nm_1285_DIAMONDCOREDRILLS',
        'eq_nm_1360_STREETSAWSSELF-PROPELLED',
        'eq_nm_1375_CONCRETEBUCKETS',
        'eq_nm_1405_FLEX-SHAFTVIBRATORS',
        'eq_nm_1450_MORTARMIXERS',
        'eq_nm_1480_POWERCONCRETEBUGGIES',
        'eq_nm_1483_POWERCONCRETEBUGGIESTRACKED',
        'eq_nm_1525_SECTIONALCONVEYORS',
        'eq_nm_1570_CARRYDECKCRANE11-15TON',
        'eq_nm_1585_CARRYDECKCRANE16-25TON',
        'eq_nm_1600_CARRYDECKCRANE4-10TON',
        'eq_nm_1840_RIDE-ONASPHALTROLLERS',
        'eq_nm_1930_DOZER70-79HP',
        'eq_nm_1945_DOZER80-89HP',
        'eq_nm_1960_DOZER90-100HP',
        'eq_nm_2005_VIDEOPIPEINSPECTION',
        'eq_nm_2050_SCISSORLIFT10-14ELECTRIC',
        'eq_nm_2065_SCISSORLIFT15-19ELECTRIC',
        'eq_nm_2080_SCISSORLIFT20-22ELECTRIC',
        'eq_nm_2095_SCISSORLIFT23-28ELECTRIC',
        'eq_nm_2110_SCISSORLIFT30-33ELECTRIC',
        'eq_nm_2125_SCISSORLIFT37-44ELECTRIC',
        'eq_nm_2130_SCISSORLIFT45-49ELECTRIC',
        'eq_nm_2395_ROTARYANDDEMOLITIONHAMMERS',
        'eq_nm_2455_25000LB-35000LBEXCAVATOR',
        'eq_nm_2470_40000LB-44000LBEXCAVATOR',
        'eq_nm_2485_45000LB-50000LBEXCAVATOR',
        'eq_nm_2500_51000LB-60000LBEXCAVATOR',
        'eq_nm_2740_ELECTRICFLOORSANDERS&EDGERS',
        'eq_nm_2755_ELECTRICTILEFLOORSTRIPPER',
        'eq_nm_2800_RIDE-ONTILEFLOORSTRIPPER',
        'eq_nm_280_AIRCOMPRESSORS375CFM-400CFM',
        'eq_nm_2815_RIDE-ONFLOORSCRUBBER',
        'eq_nm_2830_RIDE-ONFLOORSWEEPER/SCRUBBERS',
        'eq_nm_2845_WALK-BEHINDFLOORSCRUBBER',
        'eq_nm_2860_RIDE-ONSWEEPERS',
        'eq_nm_2870_OUTDOORSWEEPER',
        'eq_nm_2890_FORKLIFTACCESSORIES',
        'eq_nm_2920_FORKLIFT-INDUSTRIAL5000LB',
        'eq_nm_2921_MATERIALHANDLINGELEC5000LB',
        'eq_nm_2935_FORKLIFT-INDUSTRIAL10000LB',
        'eq_nm_295_AIRCOMPRESSORS375CFM-400CFMINSTRUMENTQUALITY',
        'eq_nm_2965_FORKLIFT-INDUSTRIAL15000LB',
        'eq_nm_2980_FORKLIFT-INDUSTRIAL20000-25000LB',
        'eq_nm_2995_FORKLIFT-INDUSTRIAL30000-36000LB',
        'eq_nm_3025_FORKLIFT-INDUSTRIAL5000-6000LB',
        'eq_nm_3040_FORKLIFT-INDUSTRIAL8000-9000LB',
        'eq_nm_3055_FORKLIFT-TELEHANDLER5000LB',
        'eq_nm_3070_FORKLIFT-TELEHANDLER10000LB',
        'eq_nm_3085_FORKLIFT-TELEHANDLER12000LB',
        'eq_nm_3087_FORKLIFT-TELEHANDLER14000LB',
        'eq_nm_3088_FORKLIFT-TELEHANDLER15000-17000LB',
        'eq_nm_3100_FORKLIFT-TELEHANDLER6000-7000LB',
        'eq_nm_3115_FORKLIFT-TELEHANDLER8000-9000LB',
        'eq_nm_3160_FORKLIFT-STRAIGHTMASTRT6000LB',
        'eq_nm_3175_FORKLIFT-STRAIGHTMASTRT8000LB',
        'eq_nm_325_AIRCOMPRESSORS600CFM-900CFM',
        'eq_nm_3265_ENVIRONMENTALAUXILIARYFUELTANKS',
        'eq_nm_340_AIRCOMPRESSORS600CFM-900CFMINSTRUMENTQUALITY',
        'eq_nm_3430_SPIDERBOXES',
        'eq_nm_3460_GENERATOR100KWTO120KW',
        'eq_nm_3475_GENERATOR150KWTO200KW',
        'eq_nm_3490_GENERATOR20KWTO40KW',
        'eq_nm_3505_GENERATOR250KWTO350KW',
        'eq_nm_3520_GENERATOR45KWTO80KW',
        'eq_nm_355_AIRCOMPRESSORS90CFM-250CFM',
        'eq_nm_3565_PORTABLEGENERATORS-GAS2.5KW-10KW',
        'eq_nm_3568_PORTABLEINVGENERATORS-GAS2.5KW-10KW',
        'eq_nm_3665_POWERCONCRETEBUGGIES',
        'eq_nm_3865_HYDRAULICBREAKERS',
        'eq_nm_4240_UTV2SEAT',
        'eq_nm_4255_UTV4SEAT',
        'eq_nm_4270_UTV6SEAT',
        'eq_nm_4300_CARTELEC2SEAT',
        'eq_nm_4315_CARTELEC3WHEEL',
        'eq_nm_4372_DIESELDRIVENSOLIDS4-14',
        'eq_nm_4410_AIRDRIVENHYDROSTATICTEST',
        'eq_nm_4495_TAMPER-JUMPINGJACK',
        'eq_nm_4645_GARDENTILLERS',
        'eq_nm_4720_HYDROSEEDER',
        'eq_nm_4735_LAWNAERATORS',
        'eq_nm_4765_LAWNMOWERS&BRUSHCUTTERS',
        'eq_nm_4855_POSTHOLEAUGERS',
        'eq_nm_4857_POSTDRIVER',
        'eq_nm_4870_SODCUTTERS',
        'eq_nm_4885_STRAWBLOWERS',
        'eq_nm_5005_LIGHTTOWERS-ALTERNATIVEFUELS',
        'eq_nm_5020_LIGHTTOWERS-DIESELTOWBEHIND',
        'eq_nm_5050_PORTABLELIGHTSTANDS',
        'eq_nm_5065_MANLIFTARTICULATING120-135COMBUSTION',
        'eq_nm_5110_MANLIFTARTICULATING30-39COMBUSTION',
        'eq_nm_5125_MANLIFTARTICULATING30-39ELECTRIC',
        'eq_nm_5140_MANLIFTARTICULATING34-39TOWABLE',
        'eq_nm_5155_MANLIFTARTICULATING40-49COMBUSTION',
        'eq_nm_5170_MANLIFTARTICULATING40-49ELECTRIC',
        'eq_nm_5185_MANLIFTARTICULATING50-59TOWABLE',
        'eq_nm_5200_MANLIFTARTICULATING60-69COMBUSTION',
        'eq_nm_5215_MANLIFTARTICULATING60-69ELECTRIC',
        'eq_nm_5245_MANLIFTARTICULATING80-89COMBUSTION',
        'eq_nm_5260_STRAIGHTBOOM100-125',
        'eq_nm_5275_STRAIGHTBOOM126-135',
        'eq_nm_5290_STRAIGHTBOOM150',
        'eq_nm_5300_STRAIGHTBOOM185',
        'eq_nm_5305_STRAIGHTBOOM40-49',
        'eq_nm_5320_STRAIGHTBOOM60-69',
        'eq_nm_5335_STRAIGHTBOOM80-89',
        'eq_nm_5365_MASTSTYLELIFT15TO20',
        'eq_nm_5380_MASTSTYLELIFT21TO26',
        'eq_nm_5395_MASTSTYLELIFT27TO33',
        'eq_nm_550_AIRCHIPPINGHAMMERS',
        'eq_nm_5545_DUCTJACKS/GENIEMATERIALLIFTS',
        'eq_nm_565_AIRPAVINGBREAKERS',
        'eq_nm_5680_PALLETTRUCKS',
        'eq_nm_580_AIRRIVETBUSTERS',
        'eq_nm_6040_PIPETHREADERS-ELECTRIC',
        'eq_nm_6115_MINI-EXCAVATOR12000LB-15000LB',
        'eq_nm_6130_MINI-EXCAVATOR16000LB-18500LB',
        'eq_nm_6145_MINI-EXCAVATOR2000LB-3500LB',
        'eq_nm_6160_MINI-EXCAVATOR2000LB-3500LBELEC',
        'eq_nm_6175_MINI-EXCAVATOR6000LB-7500LB',
        'eq_nm_6190_MINI-EXCAVATOR9000LB-11500LB',
        'eq_nm_6205_MINI-EXCAVATORSACCESSORIES',
        'eq_nm_6220_MISCELLANEOUS',
        'eq_nm_6265_ONEMANLIFTDRIVABLE12TO15ELECTRIC',
        'eq_nm_6280_ONEMANLIFTDRIVABLE20TO25ELECTRIC',
        'eq_nm_6295_ONEMANLIFTPUSHAROUND13TO24ELECTRIC',
        'eq_nm_6325_ONEMANLIFTPUSHAROUND30TO40ELECTRIC',
        'eq_nm_6595_REVERSIBLEVIBRATORYPLATECOMPACTORS',
        'eq_nm_6610_VIBRATORYPLATECOMPACTORS',
        'eq_nm_6640_COLDWATER-GAS&ELECTRIC',
        'eq_nm_6685_HOTWATER-GAS',
        'eq_nm_6760_DIAPHRAGMPUMPSGAS2-3',
        'eq_nm_685_MANLIFTATRIUM40-70',
        'eq_nm_690_MANLIFTATRIUM71-79',
        'eq_nm_700_MANLIFTATRIUM80-105',
        'eq_nm_7015_SUBMERSIBLEPUMPSELECTRIC2-3115V',
        'eq_nm_7060_TRASHPUMPGAS2-4',
        'eq_nm_7138_BOXTRUCKS',
        'eq_nm_7139_BUCKETTRUCK',
        'eq_nm_715_BACKHOEATTACHMENTS',
        'eq_nm_7165_CRANETRUCKS',
        'eq_nm_7180_DUMPTRUCKS',
        'eq_nm_7195_VAN',
        'eq_nm_7210_PICKUP',
        'eq_nm_7225_STAKEBODY',
        'eq_nm_7255_WATERTRUCKS',
        'eq_nm_7270_ROUGHTERRAINSCISSOR25-28',
        'eq_nm_7285_ROUGHTERRAINSCISSOR29-33',
        'eq_nm_7300_ROUGHTERRAINSCISSOR40-49',
        'eq_nm_730_BACKHOEEXTENDAHOE',
        'eq_nm_7315_ROUGHTERRAINSCISSOR50-59',
        'eq_nm_745_BACKHOELARGEEXTENDAHOE',
        'eq_nm_7570_RIDE-ONVIBRATORYROLLERSPADFOOT',
        'eq_nm_7585_RIDE-ONVIBRATORYROLLERSSMOOTHDRUM',
        'eq_nm_7615_RIDEONSKIDSTEERATTACHMENTS',
        'eq_nm_7630_RIDEONSKIDSTEERLOADER',
        'eq_nm_7645_SKIDSTEERATTACHMENTS',
        'eq_nm_7660_SKIDSTEERLOADER1100-1500LBTRACK',
        'eq_nm_7675_SKIDSTEERLOADER1000-1499LB',
        'eq_nm_7690_SKIDSTEERLOADER1500-2000LB',
        'eq_nm_7705_SKIDSTEERLOADER1500-2100LBTRACK',
        'eq_nm_7710_SKIDSTEERLOADER2100-2800LBTRACK',
        'eq_nm_7735_SKIDSTEERLOADER2000-2800LB',
        'eq_nm_7750_SKIDSTEERLOADER999LB&UNDER',
        'eq_nm_7900_STREETSWEEPERS',
        'eq_nm_790_BACKHOE-MINI',
        'eq_nm_7915_STUMPGRINDERS',
        'eq_nm_820_BACKHOESTANDARD',
        'eq_nm_8395_LANDSCAPE/SKIPLOADER',
        'eq_nm_8425_TRACTORS',
        'eq_nm_8455_CRASHATTENUATOR',
        'eq_nm_8470_SOLARARROW&MESSAGEBOARDS',
        'eq_nm_8530_FOLDINGRAMP&TILTDECKTRAILERS',
        'eq_nm_8545_HYDRAULICDUMPTRAILERS',
        'eq_nm_8560_PLATFORMLIFTTRAILERS',
        'eq_nm_8605_UTILITYTRAILERSWITHSIDES',
        'eq_nm_8620_WATERTRAILERS',
        'eq_nm_8650_TRENCHCOMPACTOR',
        'eq_nm_8860_RIDE-ONROCKWHEEL',
        'eq_nm_8875_RIDE-ONTRENCHERS35-50HP',
        'eq_nm_8935_WALK-BEHINDTRENCHERS',
        'eq_nm_9055_INVERTERWELDERS',
        'eq_nm_9160_PORTABLEWIREFEEDERS',
        'eq_nm_9205_WELDERSENGINEDRIVEN130AMP-600AMP',
        'eq_nm_9220_WELDINGACCESSORIES',
        'eq_nm_9250_WHEELLOADER1YD&UNDER',
        'eq_nm_9265_WHEELLOADER2-3YD',
        'eq_nm_9280_WHEELLOADER4YD',
        'eq_nm_9295_WOOD&BRUSHCHIPPERS',
        'eq_nm_9440_PORTABLEAIRSCRUBBERS',
        'eq_nm_9475_HIGH-VOLUMEFANS',
        'eq_nm_9600_1-1.5TONSPOTCOOLER',
        'eq_nm_9665_PROPANECONVECTION&RADIANTHEATERS22K-200KBT',
        'eq_nm_9670_PROPANE/NATURALGASDIRECT-FIREDHEATERS30K-2.5M',
        'eq_nm_9743_301K-400KBTUKEROSENEHEATER',
        'Division_103',
        'Division_104',
        'Division_105',
        'Division_106',
        'Division_108',
        'Division_109',
        'Division_202',
        'Division_205',
        'Division_206',
        'Division_301',
        'Division_302',
        'Division_303',
        'Division_304',
        'Division_401',
        'Division_402',
        'Division_403',
        'Division_404',
        'Division_405',
        'Division_406',
        'Division_407',
        'Division_408',
        'Division_502',
        'Division_503',
        'Division_504',
        'Division_510',
        'Division_601',
        'Division_603',
        'Division_606',
        'Division_607',
        'Division_608',
        'Division_609',
        'Division_611',
        'Division_612',
        'Division_613',
        'Division_614',
        'Division_705',
        'Division_706',
        'Division_707',
        'Division_708',
        'Division_709',
        'Division_710',
        'Division_711',
        'Division_712',
        'Division_714',
        'Division_803',
        'Division_805',
        'Division_807',
        'Division_808',
        'Division_809',
        'Division_810',
        'Division_812',
        'Division_813',
        'Division_904',
        'Division_905',
        'Division_906',
        'Division_1201',
        'Division_1301',
        'Division_1303',
        'Division_1402',
        'Division_1403',
        'RegionName_REGION01',
        'RegionName_REGION02',
        'RegionName_REGION03',
        'RegionName_REGION04',
        'RegionName_REGION05',
        'RegionName_REGION06',
        'RegionName_REGION07',
        'RegionName_REGION08',
        'RegionName_REGION09',
        'RegionName_REGION10',
        'RegionName_REGION11',
        'RegionName_REGION12',
        'RegionName_REGION14']
  label_column: 'OnRent'
  

  
